# REFERENCE
# https://github.com/Lissy93/web-check/blob/master/docker-compose.yml
# https://github.com/Lissy93/web-check?tab=readme-ov-file#deploying---option-3-docker

networks:
  webcheck:
    name: webcheck

services:
  webcheck:
    image: lissy93/web-check
    container_name: webcheck
    restart: unless-stopped
    networks:
      - webcheck
    ports:
      - ${WEBCHECK_PORT:-3000}:3000
    env_file: .env
